api:
  base_url: ${BASE_URL}
  timeout: ${TIMEOUT:30}
  headers:
    Content-Type: application/json
  endpoints:
    candlestick: /exchange/v1/public/get-candlestick

websocket:
  url: ${WS_URL:wss://uat-stream.3ona.co/exchange/v1/market}
  timeout: ${WS_TIMEOUT:30}

  subscriptions:
    book:
      method: subscribe
      channels:
        - book.BTCUSD-PERP.10
      book_subscription_type: SNAPSHOT_AND_UPDATE
      book_update_frequency: 10

logging:
  level: ${LOG_LEVEL:INFO}
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: reports/test_log.log

test_data:
  valid_instrument: BTCUSD-PERP
  valid_timeframe: M5
  invalid_instrument: INVALID-INSTRUMENT
  invalid_timeframe: INVALID
