name: Behave API Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  behave-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Behave Tests
        run: behave
