name: Behave API Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  behave-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Behave Tests
        run: behave

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.Public_Token }}
          external_repository: zf64811/Kong-cypress
          publish_branch: gh-pages
          publish_dir: ${{ github.workspace }}/reports
          keep_files: false
